title = "Botica"
baseURL= "https://blog.gabelula.com"
languageCode = "es"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
themesDir = "../.."
resourceDir = "../resources"
contentDir = "content"

DefaultContentLanguage = "es"
#SectionsPagesMenu = ["main", "about"]
enableRobotsTXT = true

#menu = ["main", "about"]

[params]
  description = "de todo como en botica"
  recent_posts_number = 1
  favicon = "img/leaf.ico"
  twitter = "https://twitter.com/gaba"
  mastodon = "https://systerserver.town/@gaba"
  github = "https://github.com/gabelula"
  rss = ""
  background_color_class = "bg-purple"
  featured_image = "/images/crater-lake.jpeg"
  about_this_web = "/about/the/web/"
  about_me = "/about/me/"
  site_logo = ""
  mainSections = ["blog","audios", "encuentros", "lecturas", "permacultura"]

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Escritos"
    title = "Escritos al aire"
    url = "/blog/"
    weight = -100

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "Que es esto?"
    url = "/about/"
    weight = -110
